### ISSUE TITLE
No screen shot using web view and logs shows error

### ISSUE THREAD

**Issue by cloudtestsoftware** [awslabs/aws-device-farm-sample-web-app-using-appium#2]
Hello,

I run your program uploading the zip after the build in the AWS device farm. The run shows successful but I could not see any screen shot.

![screen shot 2016-01-13 at 2 55 21 pm](https://cloud.githubusercontent.com/assets/15186575/12310544/b614af16-ba05-11e5-8ab6-d8f8d7740860.png)
![screen shot 2016-01-13 at 2 55 12 pm](https://cloud.githubusercontent.com/assets/15186575/12310545/b619c244-ba05-11e5-8174-d8d4feec9b1f.png)

**Comment by nikhil-dabhade** [comment]
Hi cloudtestsoftware,

I am looking in to this. 
Will update you as soon as I figure out what is happening.

**Comment by cloudtestsoftware** [comment]
Hi Nikhil,
Are you able to reproduce this issue?

**Comment by nikhil-dabhade** [comment]
Hi cloudtestsoftware,
Sorry for the delay. Yes, I was able to reproduce this issue and am working on fixing it.
Will keep you posted

**Comment by nikhil-dabhade** [comment]
Latest update: I found the source of the problem and the fix should be in by tomorrow. 
Sorry for the inconvenience.

**Comment by nikhil-dabhade** [comment]
Hi cloudtestsoftware,
The fix for the problem you were seeing is now merged. 
Please let me know if you see this or any other issue.
